services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - internal
    volumes:
      - postgres:/var/lib/postgresql/data

  # app:
  #   build: .
  #   restart: always
  #   env_file:
  #     - .env
  #   environment:
  #     POSTGRES_HOST: postgres
  #   ports:
  #     - '${PORT}:${PORT}'
  #   networks:
  #     - internal
  #   depends_on:
  #     - postgres

volumes:
  postgres:

networks:
  internal:
